package com.imse.imse.Service;

import com.imse.imse.Model.Firma;
import com.imse.imse.Repository.FirmaRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class InputService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private FirmaRepository firmaRepository;

    public String doSmth() {

        Firma n = new Firma();
        n.setName("TestFirma");
        n.setID(123);
        n.setAdresse("Wall Street");
        firmaRepository.save(n);

        Iterable<Firma> firmen;
        firmen = firmaRepository.findAll();
        for (Firma firma : firmen) {
            System.out.print("Firma: " + firma);
        }
        return "Hello";
    }
}
